# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:4

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  - bower_components/

before_script:
  - npm install bower gulp -g
  - npm install
  - bower install --allow-root

pages:
  stage: deploy
  script:
  - gulp build
  - cp -r dist public
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - gulp build
  except:
  - master
